name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the latest commit SHA
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Download model
      uses: actions/download-artifact@v2
      with:
        name: model-${{ steps.vars.outputs.sha }}
        path: model/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/g9-iris-species-predictor:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/g9-iris-species-predictor:latest

    - name: Deploy to AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_KEY }} ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
          docker-compose down
          docker-compose pull
          docker-compose up -d
        EOF