name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        python app/train.py

    - name: Run tests
      run: |
        pytest tests

    - name: Save model
      uses: actions/upload-artifact@v2
      with:
        name: model-${{ github.sha }}
        path: model/model.pkl